allowBuilds:
  bcrypt: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
minimumReleaseAgeExclude:
  - tar@7.5.7
  - tar@7.5.3
  - tar@7.5.8
  - tar@7.5.10
  - tar@7.5.11
  - tar@7.5.4
  - postcss@8.5.10
  - tar@7.5.16
  - tar@7.5.18
  - tar@7.5.19
  - tar@7.5.17
  - sharp@0.35.0
  - postcss@8.5.12
  - tar@7.5.21
  - postcss@8.5.18
overrides:
  '@types/react': 19.2.18
  '@types/react-dom': 19.2.4
